services:
  hytale-web-panel:
    container_name: hytale-web-panel
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./.docker/php/entrypoint.sh:/docker-entrypoint.sh:z
      - ./.docker/database:/var/www/database
      - ./.docker:/var/www/.docker
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "Hytale Web Panel"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
    entrypoint: /bin/sh /docker-entrypoint.sh
