services:
  hytale-web-panel:
    container_name: hytale-web-panel
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./.docker/php/entrypoint.sh:/docker-entrypoint.sh:z
      - ./.docker/database:/var/www/database
      - ./.docker:/var/www/.docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Game Server Folder
      - ./data:/var/www/html/data
    ports:
      - "8000:8000"
    entrypoint: /bin/sh /docker-entrypoint.sh
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite

  hytale:
    image: deinfreu/hytale-server:latest-alpine-liberica
    container_name: hytale-server
    environment:
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: "5520"
      PROD: "FALSE"
      DEBUG: "FALSE"
      TZ: "Indian/Maldives"
    restart: unless-stopped
    ports:
      - "5520:5520/udp"
      # Added for Web Map, Comment the line below if you don't intend on using a Web Map
      - "8080:8080"
    volumes:
      - ./data:/home/container
      - /etc/machine-id:/etc/machine-id:ro
    tty: true
    stdin_open: true